#!/bin/sh -e
#
# Bluetooth initialization on grouper
#
# Bluetooth initialization job, specifically for the Nexus 7 device (grouper),
# uses brcm-patchram-plus to patch firmware, set line discipline and write
# the bluetooth address for the device.
#


env PATCHRAM_ARGS="--patchram /etc/firmware/bcm4335c0.hcd \
                   --no2bytes \
                   --scopcm=0,4,0,0,0,0,0,3,3,0
                   --enable_hci \
                   --enable_lpm \
                   --baudrate 4000000 --use_baudrate_for_download \
                   --tosleep=50000 \
                   --bd_addr `cat /data/property/persist.service.bdroid.bdaddr`"

chmod 0660 /sys/class/rfkill/rfkill0/state
chmod 0660 /sys/class/rfkill/rfkill0/type
chgrp dialout /sys/class/rfkill/rfkill0/state
chgrp dialout /sys/class/rfkill/rfkill0/type
rfkill unblock bluetooth

/home/hciattach -f /system/vendor/firmware ttyHS99 bcm43xx 4000000 flow sleep /data/property/persist.service.bdroid.bdaddr &
#/system/bin/brcm_patchram_plus --enable_lpm --enable_hci --scopcm=0,4,0,0,0,0,0,3,3,0 --baudrate 3000000 --use_baudrate_for_download --patchram /system/vendor/firmware/bcm4335c0.hcd --no2bytes --tosleep=50000 --bd_addr `cat /data/property/persist.service.bdroid.bdaddr` /dev/ttyHS99 &
